" 通用设置 {{{
set encoding=utf-8
filetype plugin indent on "打开基于文件类型的插件和缩进
syntax enable	"开启语法高亮
syntax on "允许自定义高亮方案

set gcr=a:block-blinkon0 "关闭光标闪烁
set laststatus=2 "总是显示状态栏
set showcmd "显示命令信息
set number relativenumber "显示行号
set cursorline cursorcolumn "高亮当前行列
set hlsearch "高亮显示搜索结果

set expandtab "用空格显示制表符
set tabstop=4 "设置编辑时制表符占用4个空格
set shiftwidth=4 "设置格式化时制表符占用4个空格
set softtabstop=4
set autoindent "自动缩进

set incsearch "开启实时搜索
set noignorecase "搜索时大小写敏感
set nocompatible "关闭兼容模式
set bs=start,indent,eol "设置退格键的行为
set wildmenu "vim命令行模式智能补全

set nobackup "关闭自动备份
set noswapfile "不生成交换文件
set noautowrite "关闭自动保存
set foldmethod=marker "根据折叠代码

colorscheme desert "设置颜色主题
set t_Co=256 "256色显示
" }}}

" 插件设置 {{{
call plug#begin(fnamemodify($MYVIMRC,':p:h').'/plug')
Plug 'vim-airline/vim-airline'
call plug#end()

"
" vim-airline
"
let g:airline_powerline_fonts=1

" }}}

" 快捷键设置 {{{
	noremap <leader>ev :vsp $MYVIMRC<cr>
	noremap <leader>lv :source $MYVIMRC<cr>
" }}}

" gui版专用设置 {{{
if has('gui')
	set guifont=Powerline_Consolas:h12:cANSI "设置单字符宽度字体
    set guifontwide=黑体:h12:cGB2312 "设置双字符宽度字体
    set lines=999 columns=999 "最大化窗口
	set guioptions-=T "关闭工具栏
    set guioptions-=m "关闭菜单栏

    " 触发菜单栏的函数
    function! ToggleMenu()
        if match(&guioptions,'m') == -1
            set guioptions+=m
        else
            set guioptions-=m
        endif
    endfunction
    nnoremap <M-m> :call ToggleMenu()<cr>
endif
" }}}
